server:
  port: 18080

spring:
  application:
    name: batch
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: batch_consumer_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driverClassName: org.h2.Driver

batch:
  period:
    job: 20 # 20? ?? ??
    monitoring:
      ms: 120000 # 2? ??? ?? ??
